"""Type stubs for tomlkit.

with all my heart, 2026, mark joshwel <mark@joshwel.co>
SPDX-License-Identifier: Unlicense OR 0BSD
"""

from typing import Any, overload

class Item:
    @overload
    def get(self, key: str) -> "Item | None": ...
    @overload
    def get(self, key: str, default: "Item") -> "Item": ...
    def __getitem__(self, key: str) -> "Item": ...
    def __setitem__(self, key: str, value: "Item") -> None: ...
    def __contains__(self, key: str) -> bool: ...

class Container(Item): ...

class TOMLDocument(Container):
    @overload
    def get(self, key: str) -> Item | None: ...
    @overload
    def get(self, key: str, default: Item) -> Item: ...

class Table(Container):
    @overload
    def get(self, key: str) -> Item | None: ...
    @overload
    def get(self, key: str, default: Item) -> Item: ...

def parse(text: str) -> TOMLDocument: ...
def document() -> TOMLDocument: ...
def table() -> Table: ...
def dumps(doc: TOMLDocument) -> str: ...
