#!/usr/bin/env python3
"""scrape python docs for standard library external links.

this script scrapes docs.python.org to build a mapping of standard library
modules and their types to their documentation URLs. the output can be used
to populate meadow's external links configuration.

usage:
    uv run scripts/scrape_stdlib_links.py > stdlib_links.py

    # or with specific python version:
    uv run scripts/scrape_stdlib_links.py --version 3.13 > stdlib_links.py

output format:
    generates a python module with STDLIB_LINKS dictionary:

    STDLIB_LINKS = {
        "pathlib.Path": "https://docs.python.org/3/library/pathlib.html#pathlib.Path",
        "datetime.datetime": "https://docs.python.org/3/library/datetime.html#datetime.datetime",
        # ...
    }
"""

from __future__ import annotations

import argparse
import re
import sys
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup


BASE_URL = "https://docs.python.org/{version}/library/"

# modules to skip (internal, deprecated, or not relevant)
SKIP_MODULES = {
    "__future__",
    "__main__",
    "__builtin__",
    "builtins",  # handled specially
    "test",
    "tests",
    "idlelib",  # IDLE implementation details
}


def get_module_list(version: str) -> dict[str, str]:
    """get list of standard library modules from the library index.

    arguments:
        `version: str`
            python version (e.g., "3.13")

    returns: `dict[str, str]`
        mapping of module name to documentation URL
    """
    url = BASE_URL.format(version=version)
    response = requests.get(url, timeout=30)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")
    modules: dict[str, str] = {}

    # find the toctree with module links
    # the library index has sections with links to module pages
    for link in soup.find_all("a", class_="reference internal"):
        href = link.get("href", "")
        # module links look like "module_name.html" or "module.name.html"
        if href.endswith(".html") and not href.startswith(
            ("http", "#", "../")
        ):
            module_name = href.replace(".html", "").split("#")[0]

            # skip internal/deprecated modules
            if module_name in SKIP_MODULES or module_name.startswith(
                ("test.", "_")
            ):
                continue

            full_url = urljoin(url, href)
            modules[module_name] = full_url

    return modules


def scrape_module_types(
    module_name: str, module_url: str, version: str
) -> dict[str, str]:
    """scrape a module page for classes, functions, and exceptions.

    arguments:
        `module_name: str`
            name of the module
        `module_url: str`
            URL to the module documentation
        `version: str`
            python version

    returns: `dict[str, str]`
        mapping of fully qualified name to anchor URL
    """
    links: dict[str, str] = {}

    try:
        response = requests.get(module_url, timeout=30)
        response.raise_for_status()
    except requests.RequestException:
        return links

    soup = BeautifulSoup(response.text, "html.parser")

    # look for section headers with function/class definitions
    # python docs use dt elements with ids for definitions
    for dt in soup.find_all("dt"):
        # get the id which contains the anchor
        anchor_id = dt.get("id", "")
        if not anchor_id:
            continue

        # check if this looks like a class/function definition
        # format is usually "module.ClassName" or "module.function_name"
        if anchor_id.startswith(module_name + "."):
            # clean up the id - sometimes has extra info
            clean_id = anchor_id.split(".")[-1].split("-")[0]
            if clean_id and not clean_id.startswith(("_", "test_")):
                full_name = f"{module_name}.{clean_id}"
                anchor_url = f"{module_url}#{anchor_id}"
                links[full_name] = anchor_url

    return links


def generate_links_code(links: dict[str, str]) -> str:
    """generate python code with the links dictionary.

    arguments:
        `links: dict[str, str]`
            mapping of names to URLs

    returns: `str`
        formatted python code
    """
    lines = [
        '"""standard library external links for meadow.',
        "",
        "this module contains documentation URLs for standard library modules,",
        "classes, and functions. auto-generated by scripts/scrape_stdlib_links.py.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "# fmt: off",
        "STDLIB_LINKS: dict[str, str] = {",
    ]

    # sort by key for consistent output
    for name in sorted(links.keys()):
        url = links[name]
        lines.append(f'    "{name}": "{url}",')

    lines.extend(
        [
            "}",
            "# fmt: on",
            "",
            "",
            "def get_stdlib_link(name: str) -> str | None:",
            '    """get documentation URL for a standard library name.',
            "",
            "    arguments:",
            "        `name: str`",
            '            fully qualified name (e.g., "pathlib.Path")',
            "",
            "    returns: `str | None`",
            "        documentation URL or None if not found",
            '    """',
            "    return STDLIB_LINKS.get(name)",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    """main entry point."""
    parser = argparse.ArgumentParser(
        description="scrape python docs for standard library links",
    )
    parser.add_argument(
        "--version",
        default="3.13",
        help="python version to scrape (default: 3.13)",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="output file (default: stdout)",
    )
    parser.add_argument(
        "--modules-only",
        action="store_true",
        help="only scrape module-level links, not individual classes/functions",
    )

    args = parser.parse_args()

    print(f"scraping python {args.version} documentation...", file=sys.stderr)

    # get module list
    modules = get_module_list(args.version)
    print(f"found {len(modules)} modules", file=sys.stderr)

    all_links: dict[str, str] = {}

    # add module-level links
    for module_name, module_url in modules.items():
        all_links[module_name] = module_url

        if not args.modules_only:
            # scrape individual types from module pages
            types = scrape_module_types(module_name, module_url, args.version)
            all_links.update(types)

    print(f"total links: {len(all_links)}", file=sys.stderr)

    # generate output
    code = generate_links_code(all_links)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"written to {args.output}", file=sys.stderr)
    else:
        print(code)

    return 0


if __name__ == "__main__":
    sys.exit(main())
